// This file is auto-generated by wix-one-app-engine

export default {
  '@wix/wix-one-app-platform': () => require('@wix/wix-one-app-platform').default,
  '@wix/wixmobilecrashcourse': () => require('@wix/wixmobilecrashcourse').default,
  '@wix/wix-one-app-member-view': () => require('@wix/wix-one-app-member-view').default,
  '@wix/wix-one-app-auth': () => require('@wix/wix-one-app-auth').default,
  '@wix/native-app-wix-login': () => require('@wix/native-app-wix-login').default,
  'demo-module': () => require('demo-module').default
}
;