// This file is auto-generated by wix-one-app-engine

export default {
  '@wix/wix-one-app-platform': () => require('/Users/liatn/wixMobileCrashCourse/node_modules/@wix/wix-one-app-platform/module.places.json'),
  '@wix/wixmobilecrashcourse': () => require('/Users/liatn/wixMobileCrashCourse/module.places.json'),
  '@wix/wix-one-app-member-view': () => require('/Users/liatn/wixMobileCrashCourse/node_modules/@wix/wix-one-app-member-view/module.places.json'),
  '@wix/wix-one-app-auth': () => require('/Users/liatn/wixMobileCrashCourse/node_modules/@wix/wix-one-app-auth/module.places.json'),
  '@wix/native-app-wix-login': () => require('/Users/liatn/wixMobileCrashCourse/node_modules/@wix/native-app-wix-login/module.places.json'),
  'demo-module': () => require('/Users/liatn/wixMobileCrashCourse/demo/module.places.json')
};